<div id="dtable">
    <?php $this->title = "Data barang"; $this->headTitle($this->title); ?>
    <script src="http://www.appelsiini.net/download/jquery.jeditable.js" type="text/javascript"></script>
    <script src="http://www.appelsiini.net/download/jquery.jeditable.mini.js" type="text/javascript"></script>
    <script src="http://www.tutorialspoint.com/jquery/src/alertify/alertify.min.js"></script>
    <script>
        function reset() {
            $("#toggleCSS").attr("href", "http://www.tutorialspoint.com/jquery/src/alertify/alertify.default.css");
            alertify.set({
                labels: {
                    ok: "OK",
                    cancel: "Cancel"
                },
                delay: 2000,
                buttonReverse: false,
                buttonFocus: "ok"
            });
        }
    </script>
    </head>

    <body>
        <div class="container">
            <h2><button class="btn btn-primary" id="tambahmodal">Tambah barang</button></h2>
            <button class="btn btn-default" id="refresh" onclick="someFunc()">Refresh</button>
            <br>
            <br>

            <table id="tabel-data" class="table table-striped table-bordered" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Kode Barang</th>
                        <th>Nama Barang</th>
                        <th>Tgl masuk</th>
                        <th>Tgl keluar</th>
                        <th>Qty</th>
                        <th>Satuan</th>
                        <th>Harga</th>
                        <th>Kode Gudang</th>
                        <th>Tandai</th>
                        <th>Option</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->barang as $barang) { ?>
                    <tr id="list-barang<?php echo $barang->id; ?>">
                        <td>
                            <div class="jedit_kodebrg" id="<?php echo $barang->id; ?>"><?php echo $barang->kode_barang; ?></div>
                        </td>
                        <td>
                            <div class="jedit_namabrg" id="<?php echo $barang->id; ?>"><?php echo $barang->nama_barang; ?></div>
                        </td>
                        <td>
                            <?php echo $barang->tanggal_input; ?></td>
                        <td>
                            <?php echo $barang->tanggal_keluar; ?></td>
                        <td>
                            <div class="jedit_qty" id="<?php echo $barang->id; ?>"><?php echo $barang->quantity; ?></div>
                        </td>
                        <td>
                            <div class="jedit_satuan" id="<?php echo $barang->id; ?>"><?php echo $barang->satuan; ?></div>
                        </td>
                        <td>
                            <div class="jedit_harga" id="<?php echo $barang->id; ?>"><?php echo $barang->harga_barang; ?></div>
                        </td>
                        <td>
                            <div class="jedit_kodegd" id="<?php echo $barang->id; ?>"><?php echo $barang->kode_gudang; ?></div>
                        </td>
                        <td id="td<?php echo $barang->id; ?>">
                            <div class="btn<?php echo $barang->id; ?>"><?php if(empty($barang->tanggal_keluar)){ ?><button id='<?php echo $barang->id; ?>' class='btn btn-success'>Tandai keluar</button><?php }else{ echo '<button class="btn btn-warning disabled">Sudah Keluar</button>'; } ?></div>
                        </td>
                        <td>
                            <button class="btn btn-danger" id="<?php echo $barang->id; ?>">Delete</button>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            <p>
                * Note Klik kolom untuk mengganti cepat
                <br> Harga adalah total harga barang
            </p>
        </div>
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Tambah Barang</h4>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <div class="form-group">
                                <?php $form = new Application_Form_Barang(); echo $form; ?>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="tambahkan" class="btn btn-default">Tambah</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
        <script src="js/customize.js" type="text/javascript"></script>
</div>
