<?php 
$this->title = "Data barang";
$this->headTitle($this->title);
?>
<script src="http://www.appelsiini.net/download/jquery.jeditable.js" type="text/javascript"></script>
<script src="http://www.appelsiini.net/download/jquery.jeditable.mini.js" type="text/javascript"></script>
<div class="container">
<h2><a href="index/tambah" target="_new">Tambah barang</a></h2>
<button class="btn btn-default" id="refresh">Refresh</button>
<br><br>
<table id="tabel-data" class="table table-striped table-bordered" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kode Barang</th>
            <th>Nama Barang</th>
            <th>Tgl masuk</th>
            <th>Tgl keluar</th>
            <th>Qty</th>
            <th>Satuan</th>
            <th>Harga</th>
            <th>Kode Gudang</th>
            <th>Tandai</th>
            <th>Option</th>
        </tr>
    </thead>
    <tbody>
<?php
	foreach($this->barang as $barang)
	{
?>
<tr>
<td id="id"><?php echo $barang->id; ?></td>
<td><div class="jedit_kodebrg" id="<?php echo $barang->id; ?>"><?php echo $barang->kode_barang; ?></div></td>
<td><div class="jedit_namabrg" id="<?php echo $barang->id; ?>"><?php echo $barang->nama_barang; ?></div></td>
<td><?php echo $barang->tanggal_input; ?></td>
<td><?php echo $barang->tanggal_keluar; ?></td>
<td><div class="jedit_qty" id="<?php echo $barang->id; ?>"><?php echo $barang->quantity; ?></div></td>
<td><div class="jedit_satuan" id="<?php echo $barang->id; ?>"><?php echo $barang->satuan; ?></div></td>
<td><div class="jedit_harga" id="<?php echo $barang->id; ?>"><?php echo $barang->harga_barang; ?></div></td>
<td><div class="jedit_kodegd" id="<?php echo $barang->id; ?>"><?php echo $barang->kode_gudang; ?></div></td>
<td><?php if(empty($barang->tanggal_keluar)){ ?><a onclick="Barangkeluar(<?php echo $barang->id; ?>)" href="#">Tandai keluar</a><?php }else{ echo"Sudah Keluar"; } ?></td>
<td><a onclick="Deletefunction(<?php echo $barang->id; ?>)">Delete</a></td>
</tr>
<?php } ?>
    </tbody>
</table>
<p>
* Note
Klik kolom untuk mengganti cepat
<br>
Harga adalah total harga barang
</p>
</div>
<script>
function Deletefunction(id) {
    var txt;
    var r = confirm("Apakah anda yakin ingin menghapus data barang\ndengan id: "+ id + "?");
    if (r == true) {
        window.location.href = "index/hapus/id/"+id;
    }
    document.getElementById("demo").innerHTML = txt;
}

function Barangkeluar(id) {
    var txt;
    var r = confirm("Apakah anda yakin barang \ndengan id: "+ id + " sudah keluar dari gudang ?");
    if (r == true) {
        window.location.href = "index/editable/type/tglout/id/"+id;
    }
}
</script>
<script type="text/javascript">
 $(document).ready(function() {
	$(".jedit_kodebrg").editable("index/editable/type/kodebrg",{submit:"OK"});
	$(".jedit_namabrg").editable("index/editable/type/namabrg",{submit:"OK"});
	$(".jedit_qty").editable("index/editable/type/qty",{submit:"OK"});
	$(".jedit_harga").editable("index/editable/type/harga",{submit:"OK"});
	$(".jedit_kodegd").editable("index/editable/type/kodegd",{submit:"OK"});
        
        $(".jedit_satuan").editable("index/editable/type/satuan",{ 
            type   : 'select',
            data   : "{'kg':'kg','liter':'liter','buah':'buah'}",
            callback: function(value, settings) {
                $(this).html(jQuery.parseJSON(settings.data)[value]);
            }
            ,submit:'OK'
        });
 });

    $("#refresh").click(function() {
        $(".tabel-data").DataTable().fnReloadAjax();
    });

</script>
