<?php 
$this->title = "Tambah data";
$this->headTitle($this->title);
?>
	<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
	<script src="http://www.tutorialspoint.com/jquery/src/alertify/alertify.min.js"></script>
	<script>
		function reset () {
			$("#toggleCSS").attr("href", "http://www.tutorialspoint.com/jquery/src/alertify/alertify.default.css");
			alertify.set({
				labels : {
					ok     : "OK",
					cancel : "Cancel"
				},
				delay : 5000,
				buttonReverse : false,
				buttonFocus   : "ok"
			});
		}

</script>
<div class="container">
<h1>Tambah Barang</h1>
<h5><a href="/">Kembali</a></h5>
<div id="demo"></div>
<div class="row">
<?php echo $this->form; ?>
<button class="tambahkan">Tambah</button>
</div>
</div>

	<script type="text/javascript">
	$(document).ready(function(){
		$(".tambahkan").click(function(){
			var data = $('#barang').serialize();
			$.ajax({
				type: 'POST',
				url: "tambah",
				data: data,
				success: function() {
					reset();
					alertify.log("Berhasil menambahkan data");
					return false;
				}
			});
		});
	});
	</script>

