<script src="https://code.jquery.com/jquery-3.1.0.js"></script>
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="http://www.tutorialspoint.com/jquery/src/alertify/alertify.core.css">
<link rel="stylesheet" type="text/css" href="http://www.tutorialspoint.com/jquery/src/alertify/alertify.default.css">
<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Aplikasi pergudangan');
echo $this->doctype(); 
?>
<htmlxmlns="http://www.w3.org/1999/xhtml"xml:lang="en"lang="en">
<head>
<?php
echo $this->headMeta(); 
?>
<?php
$path = "http://zendfw.localhost/";
echo $this->headTitle(); 
?>
<script>
    $(document).ready(function(){
        $('#tabel-data').DataTable();
    });


</script>
<?php echo $this->layout()->content; ?>
